import Nav from '@/components/Nav';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppProvider } from '@/components/Provider';
import Sidebar from '@/components/Sidebar';
import Toaster from '@/components/Toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AppProvider>
          <div className="md:flex">
            <Sidebar />
            <main className="w-full relative">
              <Nav />
              <section className="mt-[3.8rem] [&>section]:pb-28 [&>section]:px-3 [&>section]:h-[100vh] [&>section]:overflow-y-auto [&>section]:overflow-x-hidden">
                {children}
              </section>
            </main>
            <Toaster />
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
