import Nav from '@/components/Nav';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppProvider } from '@/components/Provider';
import Sidebar from '@/components/Sidebar';
import Toaster from '@/components/Toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AppProvider>
          <div className="md:flex">
            <Sidebar />
            <main className="w-full relative h-[100vh] overflow-y-auto overflow-x-hidden pb-8">
              <Nav />
              <section className="mt-[4.5em] px-3">{children}</section>
            </main>
            <Toaster />
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
